add token request
neofinancial/node-flinks pull request #9
Opened 2022-08-04 16:02 UTC by KeithWyatt

2022-08-05 21:31 UTC, KeithWyatt commented
Since we accept node 14 & 16 need a code owner to update the required PR build checks to match

2022-08-05 21:53 UTC, MaxGoo approved these changes
Nice, thanks for cleaning up this library as well.

2022-08-10 22:29 UTC, iansu requested changes

2022-08-10 22:29 UTC, iansu commented on .github/workflows/ci.yml
> +          git fetch --prune
Don't need this

2022-08-10 22:29 UTC, iansu commented on .github/workflows/ci.yml
> +            ${{ runner.os }}-node-mongodb
Don't need anything related to mongo memory server

2022-08-10 22:29 UTC, iansu commented on .github/workflows/ci.yml
> +      - name: Build all
"Build all" and "Test all" aren't needed

2022-08-11 16:10 UTC, KeithWyatt commented on README.md
> -const flinks = new FlinksClient({
never needed them in the first place.

2022-08-11 16:16 UTC, KeithWyatt commented on CHANGELOG.md
> +- Add `token` command
published 3.0 but didn't release it. 
![image](https://user-images.githubusercontent.com/11324248/184180650-b4d77b2f-3fc8-4b42-845e-48fe57bdd130.png)

2022-08-11 19:10 UTC, iansu requested changes

2022-08-11 20:43 UTC, iansu approved these changes

2022-08-22 19:01 UTC, merged